[package]
name = "prisoner-cli"
authors = ["Ian Cullinane <ian@iancullinane.com>"]
version = "0.6.3"
edition = "2021"

[dependencies]
prisoner-core = { path = "../prisoner-core" }
clap = { version = "3.1.12", features = ["derive"] }
fake = "2.4"
tabled = "0.7.0"
block-id = "0.1.2"

rand = "0.8.3"
