kind: pipeline
name: default

steps:

  # - name: build
  #   image: eignhpants/image-builder
  #   environment:
  #   commands:
  #     - ./build/build.sh
  #     # - bin/main -t $DISCORD_TOKEN -b create

  - name: docker  
    image: plugins/docker
    environment:
      DOCKER_TOKEN:
        from_secret: d_token
    settings:
      config: 
        from_secret: docker-auth
      username: 
        from_secret: dh-username
      password: 
        from_secret: dh-pw
      repo: eignhpants/prisoner
      tags: 
        - ${DRONE_COMMIT_SHA}
        - latest
