kind: pipeline
name: default

steps:
  - name: docker  
    image: plugins/docker
    settings:
      username: 
        from_secret: dh-username
      password: 
        from_secret: dh-pw
      repo: eignhpants/prisoner
      tags: 
        - ${DRONE_COMMIT_SHA}
        - latest

  - name: publish-ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: sheeta_aws_key
      secret_key:
        from_secret: sheeta_aws_secret
      repo: adventurebrave.com
      dockerfile: Dockerfile
      region: us-east-2
      registry: 208744038881.dkr.ecr.us-east-2.amazonaws.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - lambda-version
